#
# Application-Aware Network Slice Manager
# Copyright (C) 2022 Int5Gent (https://5g-ppp.eu/int5gent/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.5'


services:

  tn-nssmf:
    container_name: tn-nssmf
    image: ghcr.io/nextworks-it/network-sub-slice-management-function/nssmf/int5gent/transport:0.0.1
    restart: always
    ports:
      - '8083:8083'
    command: >
      bash -c "/usr/bin/java -jar /home/ubuntu/nssmf-app-0.0.1.jar"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/nssmf
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - nssmf.eventhandler.class=it.nextworks.nfvmano.nssmf.handler.transport.nssmanagement.TransportNssLcmEventHandler
      - nssmf.provisioning.message.class=it.nextworks.nfvmano.libs.vs.common.nssmf.messages.specialized.transport.TransportInstantiatePayload
      - controller.basepath=http://10.0.50.7:4900/restconf
      - security.basic.enabled=false
      - sebastian.admin=admin
      - management.security.enabled=false
    depends_on:
      - postgres
    networks:
      - tn-nssmf
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nssmf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - 0.0.0.0:5432:5432
    networks:
      - tn-nssmf

networks:
  tn-nssmf:
    driver: bridge
